### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by Wenzel** [clearlinux/kernel-config-checker#5]
Hi,

I would be interested in integrating `kcc` in a larger project, which aims to analyze the security of operating systems.

I already manage to integrate [checksec](https://github.com/slimm609/checksec.sh), since they provide a `--json` command line option to be parsed on my Python application.

Would it be possible to have that as well, otherwise I can't process your data for hundreds of VMs.

Thanks !

**Comment by johnandersen777** [comment]
@Wenzel Do you still want this?

**Comment by Wenzel** [comment]
@pdxjohnny I closed this issue because I found another project doing more or less the same thing, 
but it seems more popular, and maybe more likely to be maintained in the future.
https://github.com/a13xp0p0v/kconfig-hardened-check

I think we will go with `kconfig-hardened-check`, otherwise i will reopen this issue.
as reference, our project where we want an integration:
https://github.com/Wenzel/oswatcher/issues/25

Thank you for the feedback !

**Comment by fenrus75** [comment]
as a team that builds an operating system and with a serious security team, we're obviously interested in any tools in this space including obviously ones we did not create... so thanks for the pointers

**Comment by Wenzel** [comment]
@fenrus75 on our side, we are interested in looking back at the history of operating system, installing all of them and gathering interesting data.

Therefore the integration of security tools, to automatically evaluate the security score of an OS in a virtual machine, and build data visualization to follow the evolution.

We are at early stages now, but the project is growing.

If you are curious, take a look at this repo:
https://github.com/Wenzel/oswatcher

**Comment by fenrus75** [comment]
I'll stick it in our regression test suite if I can :-)
